### ISSUE TITLE
Add a field in the report form to type a custom reason

### ISSUE THREAD

**Issue by xKurt** [Diduhless/Reports#5]
Hello Diduhless!

Is it possible for us to put a text for reason/s? It is very important tho
Well, we can use that if they chose the "other" option then there will be a text box!

I saw that feature [here](https://github.com/HonorGamerHD/ReportSystem)

Anyways, thank you!

**Comment by pretendlake** [comment]
Thank you for the suggestion!

I might implement something similar in the future, the purpose of this plugin was to make it as simple as possible that's why I didn't add too many features

**Comment by xKurt** [comment]
Okay, thanku sm!

**Comment by pretendlake** [comment]
Not planning on implementing this because I want to keep things simple
