### ISSUE TITLE
Implement a report list for admins

### ISSUE THREAD

**Issue by ghost** [Diduhless/Reports#6]
Adding features such as, if the player as an operator or player has permission, operator can modify the report using /reportadmin and added message to operator or player has permission when joining the game and /reportlist to show all reports.  Like this guy [report plugins](https://github.com/ConstructStudios/ReportSystem), if you add more features your plugin is very cool

Btw can you make and release plugins Friends? xD

**Comment by pretendlake** [comment]
I will store all the reports so you'll be able to view them all in a form with the /reports command, then when you select the reported player, you will have an option to dismiss the report or to teleport to him, if that works

**Comment by pretendlake** [comment]
Also, I might finish the friends plugin by the end of this month, who knows
